//! Port of Composer's `AutoloadGenerator::getStaticFile`.
//!
//! Emits `vendor/composer/autoload_static.php` — the precomputed
//! static initializer that `autoload_real.php` calls via
//! `ComposerStaticInit<hash>::getInitializer($loader)`. Composer
//! builds this with `var_export` on the same data shapes that go into
//! `autoload_psr4.php`/`autoload_classmap.php`/etc., then rewrites
//! `$vendorDir`/`$baseDir` to `__DIR__` expressions so the file is
//! self-contained.
//!
//! Path-expression rewrite (mirrors `replaceClassMapPaths` /
//! `replacePsrPaths` in Composer):
//! - `$vendorDir . '/X'` → `__DIR__ . '/..' . '/X'`
//! - `$baseDir   . '/X'` → `__DIR__ . '/../..' . '/X'`
//!
//! `var_export` formatting quirks reproduced here:
//! - opening `array (` (note the space before `(`)
//! - keys that wrap a nested array print as `'k' => \n    array (` —
//!   the trailing space after `=>` is significant for byte-equivalence
//! - 2 indent steps (Composer applies `Preg::replace('/^ {2}/m')` on
//!   `var_export`'s default 2-space indent, doubling to 4)
//!
//! The closure body inside `getInitializer` emits one
//! `$loader->X = ComposerStaticInit<hash>::$X;` per non-empty
//! `ClassLoader` property, in declaration order:
//! `prefixLengthsPsr4`, `prefixDirsPsr4`, `fallbackDirsPsr4`,
//! `prefixesPsr0`, `fallbackDirsPsr0`, `classMap`. `$files` is
//! referenced separately by `autoload_real.php` and has no closure
//! line. Composer always emits a trailing blank line before the
//! closing `}, null, ClassLoader::class);`.
//!
//! Empty PSR-0 / PSR-4 prefixes (e.g. Magento's root composer.json
//! has `"psr-0": { "": ".../lib" }`) route to the fallback fields
//! rather than the named prefix buckets — Composer's
//! `ClassLoader::set` / `setPsr4` does this routing at load time;
//! `getStaticFile` then picks the fields up via `(array) $loader`.

use std::fmt::Write;

use crate::collect::{ClassmapEntry, Entry, FileEntry};
use crate::emit::php_single_quoted;

/// `psr4` / `psr0` come in krsort order from `collect::aggregate_psr`.
/// `classmap` is alphabetical. `files` is in lockfile order (root last).
pub(crate) fn emit(
    content_hash: &str,
    psr4: &[Entry],
    psr0: &[Entry],
    classmap: &[ClassmapEntry],
    files: &[FileEntry],
) -> String {
    let mut out = String::with_capacity(2048);
    out.push_str("<?php\n\n");
    out.push_str("// autoload_static.php @generated by Composer\n\n");
    out.push_str("namespace Composer\\Autoload;\n\n");
    let _ = writeln!(out, "class ComposerStaticInit{content_hash}");
    out.push_str("{\n");

    let (named_psr4, fallback_psr4) = split_fallback(psr4);
    let (named_psr0, fallback_psr0) = split_fallback(psr0);
    let has_named_psr4 = !named_psr4.is_empty();
    let has_fallback_psr4 = !fallback_psr4.is_empty();
    let has_named_psr0 = !named_psr0.is_empty();
    let has_fallback_psr0 = !fallback_psr0.is_empty();
    let has_files = !files.is_empty();

    if has_files {
        emit_files(&mut out, files);
        out.push('\n');
    }
    if has_named_psr4 {
        emit_prefix_lengths_psr4(&mut out, &named_psr4);
        out.push('\n');
        emit_prefix_dirs_psr4(&mut out, &named_psr4);
        out.push('\n');
    }
    if has_fallback_psr4 {
        emit_fallback_dirs(&mut out, "fallbackDirsPsr4", &fallback_psr4);
        out.push('\n');
    }
    if has_named_psr0 {
        emit_prefixes_psr0(&mut out, &named_psr0);
        out.push('\n');
    }
    if has_fallback_psr0 {
        emit_fallback_dirs(&mut out, "fallbackDirsPsr0", &fallback_psr0);
        out.push('\n');
    }
    // classMap is always emitted — at minimum the InstalledVersions
    // stub row that `collect::classmap` unconditionally appends.
    emit_classmap(&mut out, classmap);
    out.push('\n');

    emit_initializer(
        &mut out,
        content_hash,
        has_named_psr4,
        has_fallback_psr4,
        has_named_psr0,
        has_fallback_psr0,
        !classmap.is_empty(),
    );

    out.push_str("}\n");
    out
}

/// Partition krsort'd PSR-* entries into (named, fallback). Entries
/// whose prefix is `""` collapse into a flat fallback path list —
/// `ClassLoader::set("", paths)` / `setPsr4("", paths)` routes those
/// to `fallbackDirsPsr0` / `fallbackDirsPsr4` at runtime. Within the
/// fallback list, ordering is the same as the input (which is itself
/// reverseSortedMap order from `aggregate_psr`).
fn split_fallback(entries: &[Entry]) -> (Vec<&Entry>, Vec<&str>) {
    let mut named: Vec<&Entry> = Vec::with_capacity(entries.len());
    let mut fallback: Vec<&str> = Vec::new();
    for e in entries {
        if e.prefix.is_empty() {
            for p in &e.paths {
                fallback.push(p.as_str());
            }
        } else {
            named.push(e);
        }
    }
    (named, fallback)
}

fn emit_files(out: &mut String, entries: &[FileEntry]) {
    out.push_str("    public static $files = array (\n");
    for e in entries {
        let _ = writeln!(
            out,
            "        '{}' => {},",
            e.identifier,
            to_dir_expr(&e.path_expr)
        );
    }
    out.push_str("    );\n");
}

/// Bucket key for the first-letter grouping. Composer keys on
/// `$prefix[0]` — the first **byte** of the prefix, not the first
/// Unicode scalar. For ASCII prefixes (every realistic PHP namespace)
/// the byte and the char coincide; modelling it as a byte makes the
/// grouping byte-accurate so a multibyte lead doesn't get its own
/// spurious bucket.
fn first_byte_bucket(prefix: &str) -> char {
    char::from(
        *prefix
            .as_bytes()
            .first()
            .expect("PSR prefix is never empty"),
    )
}

/// `$prefixLengthsPsr4` bucket-by-first-letter map. Per Composer's
/// `getStaticFile`, the outer key is `$prefix[0]` (first byte of the
/// PSR-4 prefix), and within a bucket entries appear in the same
/// krsort order as the surrounding `$psr4` list.
fn emit_prefix_lengths_psr4(out: &mut String, psr4: &[&Entry]) {
    out.push_str("    public static $prefixLengthsPsr4 = array (\n");
    let mut current_letter: Option<char> = None;
    for e in psr4 {
        let letter = first_byte_bucket(&e.prefix);
        if current_letter != Some(letter) {
            if current_letter.is_some() {
                out.push_str("        ),\n");
            }
            let _ = writeln!(
                out,
                "        {} => ",
                php_single_quoted(&letter.to_string())
            );
            out.push_str("        array (\n");
            current_letter = Some(letter);
        }
        let _ = writeln!(
            out,
            "            {} => {},",
            php_single_quoted(&e.prefix),
            e.prefix.len()
        );
    }
    if current_letter.is_some() {
        out.push_str("        ),\n");
    }
    out.push_str("    );\n");
}

fn emit_prefix_dirs_psr4(out: &mut String, psr4: &[&Entry]) {
    out.push_str("    public static $prefixDirsPsr4 = array (\n");
    for e in psr4 {
        let _ = writeln!(out, "        {} => ", php_single_quoted(&e.prefix));
        out.push_str("        array (\n");
        for (i, p) in e.paths.iter().enumerate() {
            let _ = writeln!(out, "            {} => {},", i, to_dir_expr(p));
        }
        out.push_str("        ),\n");
    }
    out.push_str("    );\n");
}

/// `$prefixesPsr0` is three-deep: first-letter bucket → namespace →
/// indexed paths. Mirrors Composer's `getStaticFile` nested loop.
fn emit_prefixes_psr0(out: &mut String, psr0: &[&Entry]) {
    out.push_str("    public static $prefixesPsr0 = array (\n");
    let mut current_letter: Option<char> = None;
    for e in psr0 {
        let letter = first_byte_bucket(&e.prefix);
        if current_letter != Some(letter) {
            if current_letter.is_some() {
                out.push_str("        ),\n");
            }
            let _ = writeln!(
                out,
                "        {} => ",
                php_single_quoted(&letter.to_string())
            );
            out.push_str("        array (\n");
            current_letter = Some(letter);
        }
        let _ = writeln!(out, "            {} => ", php_single_quoted(&e.prefix));
        out.push_str("            array (\n");
        for (i, p) in e.paths.iter().enumerate() {
            let _ = writeln!(out, "                {} => {},", i, to_dir_expr(p));
        }
        out.push_str("            ),\n");
    }
    if current_letter.is_some() {
        out.push_str("        ),\n");
    }
    out.push_str("    );\n");
}

/// Flat indexed-array emit for `fallbackDirsPsr4` / `fallbackDirsPsr0`.
/// `paths` is the concatenation of every empty-prefix entry's path
/// list. Composer formats these as a single-level
/// `array (0 => __DIR__ . '/..' . '/...', ...)` — no namespace key,
/// no per-letter bucketing.
fn emit_fallback_dirs(out: &mut String, name: &str, paths: &[&str]) {
    let _ = writeln!(out, "    public static ${name} = array (");
    for (i, p) in paths.iter().enumerate() {
        let _ = writeln!(out, "        {} => {},", i, to_dir_expr(p));
    }
    out.push_str("    );\n");
}

fn emit_classmap(out: &mut String, entries: &[ClassmapEntry]) {
    out.push_str("    public static $classMap = array (\n");
    for e in entries {
        let _ = writeln!(
            out,
            "        {} => {},",
            php_single_quoted(&e.class),
            to_dir_expr(&e.path_expr)
        );
    }
    out.push_str("    );\n");
}

#[allow(clippy::fn_params_excessive_bools)] // mirrors ClassLoader's property layout
fn emit_initializer(
    out: &mut String,
    content_hash: &str,
    has_named_psr4: bool,
    has_fallback_psr4: bool,
    has_named_psr0: bool,
    has_fallback_psr0: bool,
    has_classmap: bool,
) {
    out.push_str("    public static function getInitializer(ClassLoader $loader)\n");
    out.push_str("    {\n");
    out.push_str("        return \\Closure::bind(function () use ($loader) {\n");
    // Composer iterates the loader's properties via `(array) $loader`,
    // emitting one line per non-empty array property. The order is the
    // declaration order in ClassLoader.php: prefixLengthsPsr4,
    // prefixDirsPsr4, fallbackDirsPsr4, prefixesPsr0, fallbackDirsPsr0,
    // classMap.
    if has_named_psr4 {
        let _ = writeln!(
            out,
            "            $loader->prefixLengthsPsr4 = ComposerStaticInit{content_hash}::$prefixLengthsPsr4;"
        );
        let _ = writeln!(
            out,
            "            $loader->prefixDirsPsr4 = ComposerStaticInit{content_hash}::$prefixDirsPsr4;"
        );
    }
    if has_fallback_psr4 {
        let _ = writeln!(
            out,
            "            $loader->fallbackDirsPsr4 = ComposerStaticInit{content_hash}::$fallbackDirsPsr4;"
        );
    }
    if has_named_psr0 {
        let _ = writeln!(
            out,
            "            $loader->prefixesPsr0 = ComposerStaticInit{content_hash}::$prefixesPsr0;"
        );
    }
    if has_fallback_psr0 {
        let _ = writeln!(
            out,
            "            $loader->fallbackDirsPsr0 = ComposerStaticInit{content_hash}::$fallbackDirsPsr0;"
        );
    }
    if has_classmap {
        let _ = writeln!(
            out,
            "            $loader->classMap = ComposerStaticInit{content_hash}::$classMap;"
        );
    }
    // Composer always emits a trailing blank line inside the closure
    // body (it joins the per-field lines with `\n` and appends `\n`
    // before the closing brace). Reproduce verbatim.
    out.push('\n');
    out.push_str("        }, null, ClassLoader::class);\n");
    out.push_str("    }\n");
}

/// Convert the `$vendorDir`/`$baseDir`-relative literals stored on
/// `Entry`/`ClassmapEntry`/`FileEntry` into the `__DIR__`-relative
/// form `autoload_static.php` uses. Both source forms have the shape
/// `$prefix . '/...'`; we strip the prefix and replace it with the
/// matching `__DIR__ . '/..'` / `__DIR__ . '/../..'` token. Anything
/// the cleanup can't parse passes through unchanged — a missed rewrite
/// is loud (the byte-equivalence harness will catch it) and never
/// runtime-incorrect (PHP would still resolve the original literal).
fn to_dir_expr(expr: &str) -> String {
    if let Some(rest) = expr.strip_prefix("$vendorDir . '") {
        // rest is like `/X'`
        format!("__DIR__ . '/..' . '{rest}")
    } else if let Some(rest) = expr.strip_prefix("$baseDir . '") {
        format!("__DIR__ . '/../..' . '{rest}")
    } else {
        expr.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rewrites_vendor_and_base_paths() {
        assert_eq!(
            to_dir_expr("$vendorDir . '/acme/lib/src'"),
            "__DIR__ . '/..' . '/acme/lib/src'"
        );
        assert_eq!(
            to_dir_expr("$baseDir . '/Thing.php'"),
            "__DIR__ . '/../..' . '/Thing.php'"
        );
        assert_eq!(to_dir_expr("$baseDir . '/'"), "__DIR__ . '/../..' . '/'");
    }

    #[test]
    fn minimal_state_only_classmap_in_initializer() {
        // `collect::classmap` always appends the InstalledVersions stub,
        // so this is the smallest realistic input.
        let installed_versions = ClassmapEntry {
            class: "Composer\\InstalledVersions".to_string(),
            path_expr: "$vendorDir . '/composer/InstalledVersions.php'".to_string(),
        };
        let s = emit(
            "deadbeef",
            &[],
            &[],
            std::slice::from_ref(&installed_versions),
            &[],
        );
        assert!(s.contains("public static $classMap = array (\n"));
        assert!(!s.contains("$prefixLengthsPsr4"));
        assert!(!s.contains("$prefixesPsr0"));
        assert!(!s.contains("public static $files"));
        // Closure body has the classMap assignment, then the trailing
        // blank line Composer always emits before the bind tail.
        assert!(s.contains(
            "$loader->classMap = ComposerStaticInitdeadbeef::$classMap;\n\n        }, null, ClassLoader::class);"
        ));
    }
}
