//! PHP-source emitters for the autoload files.
//!
//! Every file Composer emits shares a fixed prolog and epilog. The
//! per-file contents between them are a single `return array(...)`
//! (or for `autoload.php`, the entry-point bootstrap). Output is
//! byte-equivalent to Composer 2.8 — golden fixtures in
//! `tests/fixtures/*/expected/` are the contract.

pub(crate) mod platform_check;
pub(crate) mod real;
pub(crate) mod static_loader;

use crate::collect::{ClassmapEntry, Entry, FileEntry};

const PSR4_HEADER: &str = "<?php\n\n// autoload_psr4.php @generated by Composer\n\n$vendorDir = dirname(__DIR__);\n$baseDir = dirname($vendorDir);\n\nreturn array(\n";
const PSR0_HEADER: &str = "<?php\n\n// autoload_namespaces.php @generated by Composer\n\n$vendorDir = dirname(__DIR__);\n$baseDir = dirname($vendorDir);\n\nreturn array(\n";
const FILES_HEADER: &str = "<?php\n\n// autoload_files.php @generated by Composer\n\n$vendorDir = dirname(__DIR__);\n$baseDir = dirname($vendorDir);\n\nreturn array(\n";
const CLASSMAP_HEADER: &str = "<?php\n\n// autoload_classmap.php @generated by Composer\n\n$vendorDir = dirname(__DIR__);\n$baseDir = dirname($vendorDir);\n\nreturn array(\n";
const ARRAY_FOOTER: &str = ");\n";

pub(crate) fn psr4(entries: &[Entry]) -> String {
    let mut out =
        String::with_capacity(PSR4_HEADER.len() + entries.len() * 64 + ARRAY_FOOTER.len());
    out.push_str(PSR4_HEADER);
    for e in entries {
        out.push_str("    ");
        out.push_str(&php_single_quoted(&e.prefix));
        out.push_str(" => array(");
        for (i, p) in e.paths.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(p);
        }
        out.push_str("),\n");
    }
    out.push_str(ARRAY_FOOTER);
    out
}

pub(crate) fn psr0(entries: &[Entry]) -> String {
    let mut out =
        String::with_capacity(PSR0_HEADER.len() + entries.len() * 64 + ARRAY_FOOTER.len());
    out.push_str(PSR0_HEADER);
    for e in entries {
        out.push_str("    ");
        out.push_str(&php_single_quoted(&e.prefix));
        out.push_str(" => array(");
        for (i, p) in e.paths.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(p);
        }
        out.push_str("),\n");
    }
    out.push_str(ARRAY_FOOTER);
    out
}

pub(crate) fn files(entries: &[FileEntry]) -> String {
    let mut out =
        String::with_capacity(FILES_HEADER.len() + entries.len() * 80 + ARRAY_FOOTER.len());
    out.push_str(FILES_HEADER);
    for e in entries {
        out.push_str("    '");
        out.push_str(&e.identifier);
        out.push_str("' => ");
        out.push_str(&e.path_expr);
        out.push_str(",\n");
    }
    out.push_str(ARRAY_FOOTER);
    out
}

pub(crate) fn classmap(entries: &[ClassmapEntry]) -> String {
    let mut out =
        String::with_capacity(CLASSMAP_HEADER.len() + entries.len() * 80 + ARRAY_FOOTER.len());
    out.push_str(CLASSMAP_HEADER);
    for e in entries {
        out.push_str("    ");
        out.push_str(&php_single_quoted(&e.class));
        out.push_str(" => ");
        out.push_str(&e.path_expr);
        out.push_str(",\n");
    }
    out.push_str(ARRAY_FOOTER);
    out
}

/// `vendor/autoload.php`. Composer 2.3+ wraps the bootstrap in a PHP
/// version guard (>=5.6). The class suffix is composer.lock's
/// `content-hash` verbatim.
pub(crate) fn entry(content_hash: &str) -> String {
    let mut out = String::with_capacity(512);
    out.push_str("<?php\n\n// autoload.php @generated by Composer\n\n");
    out.push_str("if (PHP_VERSION_ID < 50600) {\n");
    out.push_str("    if (!headers_sent()) {\n");
    out.push_str("        header('HTTP/1.1 500 Internal Server Error');\n");
    out.push_str("    }\n");
    out.push_str("    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via \"composer self-update --2.2\". Aborting.'.PHP_EOL;\n");
    out.push_str("    if (!ini_get('display_errors')) {\n");
    out.push_str("        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {\n");
    out.push_str("            fwrite(STDERR, $err);\n");
    out.push_str("        } elseif (!headers_sent()) {\n");
    out.push_str("            echo $err;\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    throw new RuntimeException($err);\n");
    out.push_str("}\n\n");
    out.push_str("require_once __DIR__ . '/composer/autoload_real.php';\n\n");
    out.push_str("return ComposerAutoloaderInit");
    out.push_str(content_hash);
    out.push_str("::getLoader();\n");
    out
}

/// PHP single-quoted string: backslashes and single-quotes are the
/// only escapes. Used for namespace prefixes (which contain `\`).
pub(crate) fn php_single_quoted(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    out.push('\'');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            _ => out.push(c),
        }
    }
    out.push('\'');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_psr4() {
        let s = psr4(&[]);
        assert!(s.ends_with("return array(\n);\n"));
    }

    #[test]
    fn quotes_namespace_backslashes() {
        assert_eq!(php_single_quoted("Acme\\Lib\\"), "'Acme\\\\Lib\\\\'");
    }
}
