//! Byte-equivalence harness — for each fixture under
//! `tests/fixtures/<name>/{input,expected}/`, runs composer-autoload's
//! `dump_autoload` against the input and asserts every file it writes
//! matches the committed expected output byte-for-byte.
//!
//! Expected outputs are generated by
//! `scripts/generate-autoload-fixtures.sh` against the pinned
//! Composer version (see `REFERENCE_COMPOSER_VERSION` in lib.rs).
//! The fixture input also commits the materialized `vendor/<pkg>/`
//! source tree for any path-repo packages — classmap scanning needs
//! the installed file layout (which Composer would produce via
//! `composer install`; composer-autoload takes that layout as
//! pre-existing and only emits the autoload metadata).
//! Re-run the fixture script + commit when bumping the pin.

use composer_autoload::{DumpRequest, dump_autoload};
use std::path::{Path, PathBuf};

const FIXTURES_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");

/// Always-on: every fixture dir has `input/composer.json` and a
/// non-empty `expected/` tree. Fast (~milliseconds) — catches a broken
/// fixture-gen run or a hand-edit before the rest of the suite would.
#[test]
fn fixtures_are_well_formed() {
    let dirs = fixture_dirs();
    assert!(!dirs.is_empty(), "no fixtures under {FIXTURES_DIR}");
    for dir in &dirs {
        let name = dir.file_name().unwrap().to_string_lossy();
        let input_json = dir.join("input").join("composer.json");
        assert!(
            input_json.is_file(),
            "fixture {name}: missing input/composer.json"
        );
        let expected = dir.join("expected");
        assert!(expected.is_dir(), "fixture {name}: missing expected/ dir");
        let count = walk(&expected).count();
        assert!(
            count > 0,
            "fixture {name}: expected/ is empty — did generate-autoload-fixtures.sh run?"
        );
    }
}

/// Files composer-autoload currently emits. Other files in `expected/`
/// (`autoload_real.php`, `autoload_static.php`, installed.{json,php}) are
/// produced by later phases or by full `composer install`; the
/// harness ignores them until those phases land.
const EMITTED: &[&str] = &[
    "vendor/autoload.php",
    "vendor/composer/autoload_namespaces.php",
    "vendor/composer/autoload_psr4.php",
    "vendor/composer/autoload_classmap.php",
    "vendor/composer/autoload_files.php",
    "vendor/composer/autoload_real.php",
    "vendor/composer/autoload_static.php",
    "vendor/composer/platform_check.php",
    "vendor/composer/installed.json",
    "vendor/composer/installed.php",
    "vendor/composer/ClassLoader.php",
    "vendor/composer/InstalledVersions.php",
    "vendor/composer/LICENSE",
];

#[test]
fn byte_equivalence_against_composer() {
    let mut failures: Vec<String> = vec![];

    for dir in fixture_dirs() {
        let name = dir.file_name().unwrap().to_string_lossy().into_owned();

        let work = match copy_input_to_tempdir(&dir) {
            Ok(p) => p,
            Err(e) => {
                failures.push(format!("{name}: setup failed: {e}"));
                continue;
            }
        };

        let flags = parse_flags(&dir.join("input"));
        let req = DumpRequest {
            project_root: work.path(),
            optimize: flags.optimize,
            classmap_authoritative: flags.classmap_authoritative,
            no_dev: flags.no_dev,
            apcu_autoloader: flags.apcu_autoloader,
            apcu_prefix: flags.apcu_prefix.clone(),
            autoloader_suffix: flags.autoloader_suffix.clone(),
        };
        if let Err(e) = dump_autoload(&req) {
            failures.push(format!("{name}: dump_autoload failed: {e}"));
            continue;
        }

        let expected_root = dir.join("expected");
        for rel in EMITTED {
            let expected_path = expected_root.join(rel);
            let actual_path = work.path().join(rel);
            // autoload_files.php is only emitted when any package has
            // a files entry. If neither side wrote it, that's fine.
            match (expected_path.exists(), actual_path.exists()) {
                (false, false) => continue,
                (true, false) => {
                    failures.push(format!(
                        "{name}: composer-autoload did not produce {rel} (Composer did)"
                    ));
                    continue;
                }
                (false, true) => {
                    failures.push(format!(
                        "{name}: composer-autoload produced {rel} but Composer did not"
                    ));
                    continue;
                }
                (true, true) => {}
            }
            let expected_bytes = std::fs::read(&expected_path).unwrap();
            let actual_bytes = std::fs::read(&actual_path).unwrap();
            if expected_bytes != actual_bytes {
                failures.push(format_diff(&name, rel, &expected_bytes, &actual_bytes));
            }
        }
    }

    assert!(
        failures.is_empty(),
        "{} byte-equivalence failures:\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}

fn format_diff(name: &str, rel: &str, expected: &[u8], actual: &[u8]) -> String {
    let exp_str = std::str::from_utf8(expected).unwrap_or("<non-utf8>");
    let act_str = std::str::from_utf8(actual).unwrap_or("<non-utf8>");
    format!(
        "{name}: {} differs ({} expected bytes vs {} actual)\n--- expected ---\n{exp_str}\n--- actual ---\n{act_str}",
        rel,
        expected.len(),
        actual.len()
    )
}

/// Flags pulled from a fixture's optional `input/flags` file.
/// Format is one `key=value` per line. Bools default to false;
/// string-valued flags (`apcu_prefix`, `autoloader_suffix`) default
/// to None. Used by both this harness and
/// `scripts/generate-autoload-fixtures.sh` so the fixture is
/// regenerated under the same flag combo the harness asserts under.
#[derive(Default)]
struct FixtureFlags {
    optimize: bool,
    classmap_authoritative: bool,
    no_dev: bool,
    apcu_autoloader: bool,
    apcu_prefix: Option<String>,
    autoloader_suffix: Option<String>,
}

fn parse_flags(input_dir: &Path) -> FixtureFlags {
    let path = input_dir.join("flags");
    let Ok(text) = std::fs::read_to_string(&path) else {
        return FixtureFlags::default();
    };
    let mut flags = FixtureFlags::default();
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((k, v)) = line.split_once('=') else {
            continue;
        };
        let v_str = v.trim();
        let v_bool = v_str == "true";
        match k.trim() {
            "optimize" => flags.optimize = v_bool,
            "classmap_authoritative" => flags.classmap_authoritative = v_bool,
            "no_dev" => flags.no_dev = v_bool,
            "apcu_autoloader" => flags.apcu_autoloader = v_bool,
            "apcu_prefix" => flags.apcu_prefix = Some(v_str.to_string()),
            "autoloader_suffix" => flags.autoloader_suffix = Some(v_str.to_string()),
            _ => {}
        }
    }
    flags
}

fn fixture_dirs() -> Vec<PathBuf> {
    let mut dirs: Vec<PathBuf> = std::fs::read_dir(FIXTURES_DIR)
        .expect("read fixtures dir")
        .filter_map(std::result::Result::ok)
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .collect();
    dirs.sort();
    dirs
}

fn walk(root: &Path) -> impl Iterator<Item = PathBuf> {
    let mut out = vec![];
    walk_into(root, root, &mut out);
    out.sort();
    out.into_iter()
}

fn walk_into(root: &Path, dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(std::result::Result::ok) {
        let p = entry.path();
        if p.is_dir() {
            walk_into(root, &p, out);
        } else if p.is_file()
            && let Ok(rel) = p.strip_prefix(root)
        {
            out.push(rel.to_path_buf());
        }
    }
}

fn copy_input_to_tempdir(fixture_dir: &Path) -> std::io::Result<TempDir> {
    let td = TempDir::new()?;
    copy_dir(&fixture_dir.join("input"), td.path())?;
    Ok(td)
}

fn copy_dir(src: &Path, dst: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(dst)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());
        if src_path.is_dir() {
            copy_dir(&src_path, &dst_path)?;
        } else {
            std::fs::copy(&src_path, &dst_path)?;
        }
    }
    Ok(())
}

/// Minimal tempdir helper (no `tempfile` dep — composer-autoload has
/// no production dependencies yet, and we want to keep dev-deps lean
/// per the conventions surveyed in the test-suite plan).
struct TempDir {
    path: PathBuf,
}

impl TempDir {
    fn new() -> std::io::Result<Self> {
        let base = std::env::temp_dir();
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path = base.join(format!(
            "composer-autoload-fx-{nanos}-{}",
            std::process::id()
        ));
        std::fs::create_dir(&path)?;
        Ok(Self { path })
    }
    fn path(&self) -> &Path {
        &self.path
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.path);
    }
}
