//! `magento/magento-composer-installer` — native deploy.
//!
//! On install of a Magento 2 component, the plugin copies the files
//! declared in the package's `extra.map` into the Magento root, applies
//! `extra.chmod` permission masks, and writes `app/etc/vendor_path.php`.
//! We reproduce that effect without running the plugin.
//!
//! Ground truth (from a published `magento/magento2-base`):
//! ```json
//! "type": "magento2-component",
//! "extra": {
//!   "map":   [ [".htaccess", ".htaccess"], ["index.php", "index.php"],
//!              ["pub/index.php", "pub/index.php"], ... ],
//!   "chmod": [ { "mask": "0755", "path": "bin/magento" } ]
//! }
//! ```
//! `map` entries are `[source-relative-to-package, dest-relative-to-root]`
//! pairs; `chmod` entries are `{ mask: <octal-string>, path: <root-rel> }`.
//!
//! `app/etc/vendor_path.php` is *not* in the map — the plugin generates
//! it — so we emit [`VENDOR_PATH_PHP`] separately (see the orchestrator).

use std::path::{Path, PathBuf};

use eyre::{Result, eyre};
use serde_json::Value;

/// Contents Magento ships in `app/etc/vendor_path.php`. Magento's
/// `bootstrap.php` `require`s this file and prepends the returned value
/// to the base path to locate the Composer `vendor/` dir. Generated by
/// the installer rather than mapped, hence a constant here.
pub const VENDOR_PATH_PHP: &str =
    "<?php\n/**\n * Path to Composer vendor directory\n */\nreturn './vendor';\n";

/// Magento 2 component package types handled by
/// `magento/magento-composer-installer`. Only these carry `extra.map` /
/// `extra.chmod` that the plugin acts on; gating on type keeps us from
/// touching an unrelated package that happens to ship an `extra.map`
/// blob for some other plugin.
const MAGENTO2_TYPES: &[&str] = &[
    "magento2-component",
    "magento2-module",
    "magento2-theme",
    "magento2-language",
    "magento2-library",
];

/// True when `package_type` is one of the Magento 2 component types the
/// deploy plugin supports.
#[must_use]
pub fn is_magento2_type(package_type: Option<&str>) -> bool {
    package_type.is_some_and(|t| MAGENTO2_TYPES.contains(&t))
}

/// A single `extra.chmod` permission entry: an octal `mask` applied to a
/// `path` relative to the Magento root.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ChmodEntry {
    /// Permission bits, parsed from the octal string Composer stores
    /// (e.g. `"0755"` → `0o755`).
    pub mask: u32,
    /// Target path, relative to the project (Magento) root.
    pub path: String,
}

/// The materialization a single package's `extra` declares: files to
/// copy into the root and permissions to set afterwards. Empty plans are
/// possible (e.g. a `magento2-module` with no `map`); the executor then
/// does nothing.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct DeployPlan {
    /// `(source-relative-to-package, dest-relative-to-root)` copy pairs,
    /// in declared order.
    pub map: Vec<(String, String)>,
    /// Permission masks to apply after copying.
    pub chmod: Vec<ChmodEntry>,
    /// Whether the package is a `magento2-component` — the carrier that
    /// triggers `app/etc/vendor_path.php` generation. Tracked here so the
    /// orchestrator can decide whether to emit it without re-checking the
    /// type.
    pub is_component: bool,
}

/// Outcome of [`apply_deploy`], for the install summary.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct DeployStats {
    /// Number of files copied into the root (directories aren't counted).
    pub files_copied: u64,
    /// Number of `chmod` masks applied (no-op on non-Unix).
    pub chmods_applied: u64,
}

impl DeployStats {
    fn add(&mut self, other: DeployStats) {
        self.files_copied += other.files_copied;
        self.chmods_applied += other.chmods_applied;
    }
}

/// Build a [`DeployPlan`] from a package's `type` and `extra`. Returns
/// `None` when the package isn't a Magento 2 component type (nothing to
/// deploy), and `Some(empty)` when it is but declares no `map`/`chmod`.
///
/// `map` and `chmod` entries that don't match the expected JSON shape are
/// skipped rather than failing the whole install — a malformed entry in a
/// third-party package shouldn't block the install. Skips are surfaced
/// via the returned plan being smaller than the raw arrays; the caller
/// can warn if it wants to.
#[must_use]
pub fn plan_deploy(package_type: Option<&str>, extra: &Value) -> Option<DeployPlan> {
    if !is_magento2_type(package_type) {
        return None;
    }

    let mut map = Vec::new();
    if let Some(entries) = extra.get("map").and_then(Value::as_array) {
        for entry in entries {
            // Each entry is a two-element array [source, dest].
            if let Some(arr) = entry.as_array()
                && let (Some(src), Some(dst)) = (
                    arr.first().and_then(Value::as_str),
                    arr.get(1).and_then(Value::as_str),
                )
            {
                map.push((src.to_string(), dst.to_string()));
            }
        }
    }

    let mut chmod = Vec::new();
    if let Some(entries) = extra.get("chmod").and_then(Value::as_array) {
        for entry in entries {
            let mask = entry.get("mask").and_then(Value::as_str);
            let path = entry.get("path").and_then(Value::as_str);
            if let (Some(mask), Some(path)) = (mask, path)
                && let Ok(mask) = u32::from_str_radix(mask.trim_start_matches("0o"), 8)
            {
                chmod.push(ChmodEntry {
                    mask,
                    path: path.to_string(),
                });
            }
        }
    }

    Some(DeployPlan {
        map,
        chmod,
        is_component: package_type == Some("magento2-component"),
    })
}

/// Apply a [`DeployPlan`]: copy every mapped path from `package_dir` into
/// `project_root`, then apply the chmod masks. Idempotent — existing
/// destinations are overwritten so a re-extract restores pristine root
/// files (Composer's copy strategy throws on conflict unless
/// `extra.magento-force`; a package manager re-running its own install
/// always wants the force behavior, so we overwrite unconditionally).
pub fn apply_deploy(
    plan: &DeployPlan,
    package_dir: &Path,
    project_root: &Path,
) -> Result<DeployStats> {
    let mut stats = DeployStats::default();

    for (source, dest) in &plan.map {
        if source.contains('*') {
            // Glob mappings exist in the M1 installer but not in M2
            // component maps (magento2-base uses literal pairs). Defer
            // rather than silently mis-handle.
            return Err(eyre!(
                "extra.map glob patterns are not yet supported (entry: {source} => {dest})"
            ));
        }
        let src_path = package_dir.join(rel(source));
        let dst_path = project_root.join(rel(dest));
        stats.add(copy_path(&src_path, &dst_path)?);
    }

    for entry in &plan.chmod {
        let target = project_root.join(rel(&entry.path));
        if apply_chmod(&target, entry.mask)? {
            stats.chmods_applied += 1;
        }
    }

    Ok(stats)
}

/// Strip a leading `/` so a map/chmod path is always treated as
/// project-relative even if it's authored with a leading slash, and
/// normalize separators on Windows.
fn rel(p: &str) -> PathBuf {
    PathBuf::from(p.trim_start_matches('/'))
}

/// Copy a file or directory tree from `src` to `dst`, creating parent
/// directories as needed and overwriting existing files. Mirrors the
/// copy deploy strategy's file-to-file and dir-to-dir paths for the
/// literal (non-glob) mappings Magento 2 components use.
fn copy_path(src: &Path, dst: &Path) -> Result<DeployStats> {
    let meta = std::fs::symlink_metadata(src)
        .map_err(|e| eyre!("deploy source {} unreadable: {e}", src.display()))?;

    if let Some(parent) = dst.parent() {
        std::fs::create_dir_all(parent).map_err(|e| eyre!("creating {}: {e}", parent.display()))?;
    }

    if meta.is_dir() {
        copy_dir_recursive(src, dst)
    } else {
        // Replace any existing destination (file or dangling symlink).
        if dst.exists() || std::fs::symlink_metadata(dst).is_ok() {
            let _ = std::fs::remove_file(dst);
        }
        std::fs::copy(src, dst)
            .map_err(|e| eyre!("copying {} -> {}: {e}", src.display(), dst.display()))?;
        Ok(DeployStats {
            files_copied: 1,
            chmods_applied: 0,
        })
    }
}

/// Recursively copy a directory tree, counting files copied. Directories
/// are created if absent; files are overwritten.
fn copy_dir_recursive(src: &Path, dst: &Path) -> Result<DeployStats> {
    let mut stats = DeployStats::default();
    std::fs::create_dir_all(dst).map_err(|e| eyre!("creating {}: {e}", dst.display()))?;

    for entry in std::fs::read_dir(src).map_err(|e| eyre!("reading {}: {e}", src.display()))? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if file_type.is_dir() {
            stats.add(copy_dir_recursive(&from, &to)?);
        } else {
            if to.exists() || std::fs::symlink_metadata(&to).is_ok() {
                let _ = std::fs::remove_file(&to);
            }
            std::fs::copy(&from, &to)
                .map_err(|e| eyre!("copying {} -> {}: {e}", from.display(), to.display()))?;
            stats.files_copied += 1;
        }
    }
    Ok(stats)
}

/// Apply an octal permission `mask` to `target`. Unix-only; a no-op that
/// returns `false` on other platforms (Magento's services stack is
/// Unix-only anyway). Returns `false` (not an error) when the target
/// doesn't exist — a `chmod` entry for a file a particular package
/// variant didn't ship shouldn't fail the install.
#[cfg(unix)]
fn apply_chmod(target: &Path, mask: u32) -> Result<bool> {
    use std::os::unix::fs::PermissionsExt;
    if !target.exists() {
        return Ok(false);
    }
    std::fs::set_permissions(target, std::fs::Permissions::from_mode(mask))
        .map_err(|e| eyre!("chmod {:o} {}: {e}", mask, target.display()))?;
    Ok(true)
}

#[cfg(not(unix))]
fn apply_chmod(_target: &Path, _mask: u32) -> Result<bool> {
    Ok(false)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn non_magento_type_has_no_plan() {
        assert!(plan_deploy(Some("library"), &json!({"map": [["a", "b"]]})).is_none());
        assert!(plan_deploy(None, &json!({})).is_none());
    }

    #[test]
    fn parses_map_and_chmod() {
        let extra = json!({
            "map": [["index.php", "index.php"], ["pub/", "pub/"]],
            "chmod": [{"mask": "0755", "path": "bin/magento"}]
        });
        let plan = plan_deploy(Some("magento2-component"), &extra).unwrap();
        assert!(plan.is_component);
        assert_eq!(
            plan.map,
            vec![
                ("index.php".to_string(), "index.php".to_string()),
                ("pub/".to_string(), "pub/".to_string())
            ]
        );
        assert_eq!(
            plan.chmod,
            vec![ChmodEntry {
                mask: 0o755,
                path: "bin/magento".into()
            }]
        );
    }

    #[test]
    fn skips_malformed_entries() {
        let extra = json!({
            "map": [["ok", "ok"], ["missing-dest"], "not-an-array"],
            "chmod": [{"mask": "0755"}, {"path": "x"}, {"mask": "zzz", "path": "y"}]
        });
        let plan = plan_deploy(Some("magento2-module"), &extra).unwrap();
        assert_eq!(plan.map, vec![("ok".to_string(), "ok".to_string())]);
        assert!(plan.chmod.is_empty());
        assert!(!plan.is_component);
    }

    #[test]
    fn copies_files_and_dirs_into_root() {
        let pkg = tempfile::tempdir().unwrap();
        let root = tempfile::tempdir().unwrap();
        std::fs::write(pkg.path().join("index.php"), b"<?php // front controller").unwrap();
        std::fs::create_dir_all(pkg.path().join("pub/media")).unwrap();
        std::fs::write(pkg.path().join("pub/index.php"), b"pub").unwrap();
        std::fs::write(pkg.path().join("pub/media/.htaccess"), b"deny").unwrap();

        let plan = DeployPlan {
            map: vec![
                ("index.php".into(), "index.php".into()),
                ("pub".into(), "pub".into()),
            ],
            chmod: vec![],
            is_component: true,
        };
        let stats = apply_deploy(&plan, pkg.path(), root.path()).unwrap();

        assert!(root.path().join("index.php").is_file());
        assert!(root.path().join("pub/index.php").is_file());
        assert!(root.path().join("pub/media/.htaccess").is_file());
        assert_eq!(stats.files_copied, 3);
    }

    #[test]
    fn overwrites_existing_destination() {
        let pkg = tempfile::tempdir().unwrap();
        let root = tempfile::tempdir().unwrap();
        std::fs::write(pkg.path().join("index.php"), b"new").unwrap();
        std::fs::write(root.path().join("index.php"), b"old").unwrap();

        let plan = DeployPlan {
            map: vec![("index.php".into(), "index.php".into())],
            ..Default::default()
        };
        apply_deploy(&plan, pkg.path(), root.path()).unwrap();
        assert_eq!(
            std::fs::read(root.path().join("index.php")).unwrap(),
            b"new"
        );
    }

    #[test]
    fn glob_source_is_rejected() {
        let pkg = tempfile::tempdir().unwrap();
        let root = tempfile::tempdir().unwrap();
        let plan = DeployPlan {
            map: vec![("locale/*".into(), "app/locale".into())],
            ..Default::default()
        };
        assert!(apply_deploy(&plan, pkg.path(), root.path()).is_err());
    }

    #[cfg(unix)]
    #[test]
    fn applies_chmod_mask() {
        use std::os::unix::fs::PermissionsExt;
        let pkg = tempfile::tempdir().unwrap();
        let root = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(pkg.path().join("bin")).unwrap();
        std::fs::write(pkg.path().join("bin/magento"), b"#!/usr/bin/env php").unwrap();

        let plan = DeployPlan {
            map: vec![("bin/magento".into(), "bin/magento".into())],
            chmod: vec![ChmodEntry {
                mask: 0o755,
                path: "bin/magento".into(),
            }],
            is_component: true,
        };
        let stats = apply_deploy(&plan, pkg.path(), root.path()).unwrap();
        assert_eq!(stats.chmods_applied, 1);
        let mode = std::fs::metadata(root.path().join("bin/magento"))
            .unwrap()
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, 0o755);
    }

    #[cfg(unix)]
    #[test]
    fn chmod_missing_target_is_noop() {
        let root = tempfile::tempdir().unwrap();
        assert!(!apply_chmod(&root.path().join("nope"), 0o755).unwrap());
    }
}
