//! The per-package apply pass the install orchestrator drives after a package
//! has been (re-)extracted pristine.
//!
//! For each target package it applies every patch in order into the package's
//! install directory, writes the `PATCHES.txt` report (cweagans parity), and
//! returns the new fingerprint to record in `patches.lock.json`. A partial or
//! failed apply yields **no** fingerprint, so the next run re-extracts the
//! package pristine and retries rather than trusting a half-patched tree.

use std::io::Write;
use std::path::Path;

use eyre::{Result, bail};

use crate::apply::{ApplyOptions, apply_patch_text};
use crate::model::FailureMode;
use crate::plan::{MaterializedPatch, fingerprint};
use crate::report::ApplyReport;

/// Result of applying one package's patches.
#[derive(Debug, Default)]
pub struct PackageApplyResult {
    /// The fingerprint to record — `Some` only if **every** patch applied.
    pub fingerprint: Option<String>,
    /// Per-patch apply reports for the ones that succeeded.
    pub reports: Vec<ApplyReport>,
    /// Non-fatal warnings (skipped patches, report-write failures).
    pub warnings: Vec<String>,
}

/// Apply all of `patches` (in order) into `base_dir`.
///
/// `base_dir` is the package's install directory; patch headers strip down
/// into it via the `-p` level. On `FailureMode::Abort` the first failure
/// returns `Err`; on `SkipAndWarn` failures are collected and the package
/// gets no fingerprint.
pub fn apply_package_patches(
    base_dir: &Path,
    package: &str,
    patches: &[MaterializedPatch],
    failure_mode: FailureMode,
    skip_report: bool,
) -> Result<PackageApplyResult> {
    let mut result = PackageApplyResult::default();
    let mut applied: Vec<&MaterializedPatch> = Vec::new();
    let mut all_ok = true;

    for patch in patches {
        let text = std::fs::read_to_string(&patch.local_path)
            .map_err(|e| eyre::eyre!("reading patch `{}`: {e}", patch.local_path.display()))?;
        let opts = ApplyOptions {
            depth: patch.depth,
            ..ApplyOptions::default()
        };
        match apply_patch_text(base_dir, &text, &opts) {
            Ok(report) => {
                applied.push(patch);
                result.reports.push(report);
            }
            Err(e) => {
                all_ok = false;
                let msg = format!(
                    "patch `{}` for `{package}` failed to apply: {e}",
                    patch.description
                );
                match failure_mode {
                    FailureMode::Abort => bail!(msg),
                    FailureMode::SkipAndWarn => result.warnings.push(msg),
                }
            }
        }
    }

    if !skip_report
        && !applied.is_empty()
        && let Err(e) = write_patches_txt(base_dir, &applied)
    {
        result.warnings.push(format!(
            "could not write PATCHES.txt in `{}`: {e}",
            base_dir.display()
        ));
    }

    // Only a fully-applied set earns a fingerprint; a partial apply must be
    // re-done from pristine next run.
    if all_ok {
        result.fingerprint = Some(fingerprint(patches));
    }

    Ok(result)
}

/// The `PATCHES.txt` preamble, byte-compatible with the cweagans plugin's.
const PATCHES_TXT_HEADER: &str = "This file was automatically generated by composer-patches \
     (a native reimplementation of cweagans/composer-patches)\n\
     Patches applied to this directory:\n\n";

/// Format one entry block per applied patch (description + `Source:` line),
/// in cweagans' layout.
fn patches_txt_entries(applied: &[&MaterializedPatch]) -> String {
    let mut out = String::new();
    for patch in applied {
        out.push_str(&patch.description);
        out.push('\n');
        out.push_str("Source: ");
        out.push_str(&patch.origin);
        out.push_str("\n\n\n");
    }
    out
}

/// Write `PATCHES.txt` in `dir`, listing the applied patches in cweagans'
/// format so the report is interchangeable with the PHP plugin's.
fn write_patches_txt(dir: &Path, applied: &[&MaterializedPatch]) -> Result<()> {
    let mut out = String::from(PATCHES_TXT_HEADER);
    out.push_str(&patches_txt_entries(applied));
    std::fs::write(dir.join("PATCHES.txt"), out)?;
    Ok(())
}

/// Append entries to a package's `PATCHES.txt`, creating it (with the standard
/// header) if absent. This is how a project-root ("top-level") patch records
/// itself in every package it touches: the package's own `PATCHES.txt` (if it
/// has package-scoped patches) already carries the header + those entries, and
/// the root patch is appended so each patched directory's audit trail is
/// complete. A no-op for an empty `applied` slice.
pub fn append_patches_txt(dir: &Path, applied: &[&MaterializedPatch]) -> Result<()> {
    if applied.is_empty() {
        return Ok(());
    }
    let path = dir.join("PATCHES.txt");
    let mut body = String::new();
    if !path.exists() {
        body.push_str(PATCHES_TXT_HEADER);
    }
    body.push_str(&patches_txt_entries(applied));
    let mut f = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&path)?;
    f.write_all(body.as_bytes())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::DepthSpec;
    use std::fs;
    use tempfile::tempdir;

    fn write_patch(dir: &Path, name: &str, body: &str) -> MaterializedPatch {
        let path = dir.join(name);
        fs::write(&path, body).unwrap();
        MaterializedPatch {
            description: format!("patch {name}"),
            origin: name.to_string(),
            local_path: path,
            content_sha256: crate::content_sha256(body.as_bytes()),
            depth: DepthSpec::Auto,
        }
    }

    #[test]
    fn applies_and_writes_report_and_fingerprint() {
        let work = tempdir().unwrap();
        let base = work.path().join("pkg");
        fs::create_dir_all(base.join("src")).unwrap();
        fs::write(base.join("src/Foo.php"), "a\nb\nc\n").unwrap();

        let pdir = tempdir().unwrap();
        let patch = write_patch(
            pdir.path(),
            "fix.patch",
            "--- a/src/Foo.php\n+++ b/src/Foo.php\n@@ -1,3 +1,3 @@\n a\n-b\n+B\n c\n",
        );

        let res = apply_package_patches(&base, "vendor/pkg", &[patch], FailureMode::Abort, false)
            .unwrap();
        assert!(res.fingerprint.is_some());
        assert_eq!(
            fs::read_to_string(base.join("src/Foo.php")).unwrap(),
            "a\nB\nc\n"
        );
        let report = fs::read_to_string(base.join("PATCHES.txt")).unwrap();
        assert!(report.contains("Source: fix.patch"));
    }

    #[test]
    fn skip_mode_drops_fingerprint_on_failure() {
        let work = tempdir().unwrap();
        let base = work.path().join("pkg");
        fs::create_dir_all(&base).unwrap();
        // Target file absent → the patch cannot apply.
        let pdir = tempdir().unwrap();
        let patch = write_patch(
            pdir.path(),
            "bad.patch",
            "--- a/missing.txt\n+++ b/missing.txt\n@@ -1 +1 @@\n-x\n+y\n",
        );
        let res = apply_package_patches(
            &base,
            "vendor/pkg",
            &[patch],
            FailureMode::SkipAndWarn,
            false,
        )
        .unwrap();
        assert!(
            res.fingerprint.is_none(),
            "partial apply earns no fingerprint"
        );
        assert_eq!(res.warnings.len(), 1);
    }

    #[test]
    fn abort_mode_errors_on_failure() {
        let work = tempdir().unwrap();
        let base = work.path().join("pkg");
        fs::create_dir_all(&base).unwrap();
        let pdir = tempdir().unwrap();
        let patch = write_patch(
            pdir.path(),
            "bad.patch",
            "--- a/missing.txt\n+++ b/missing.txt\n@@ -1 +1 @@\n-x\n+y\n",
        );
        assert!(
            apply_package_patches(&base, "vendor/pkg", &[patch], FailureMode::Abort, false)
                .is_err()
        );
    }

    #[test]
    fn append_creates_then_appends_with_single_header() {
        let dir = tempdir().unwrap();
        let pdir = dir.path();
        let one = write_patch(pdir, "one.patch", "");
        let two = write_patch(pdir, "two.patch", "");

        // First append into an empty dir creates the file with the header.
        append_patches_txt(pdir, &[&one]).unwrap();
        let after_first = fs::read_to_string(pdir.join("PATCHES.txt")).unwrap();
        assert!(after_first.starts_with("This file was automatically generated"));
        assert!(after_first.contains("Source: one.patch"));

        // A second append adds the entry without re-emitting the header.
        append_patches_txt(pdir, &[&two]).unwrap();
        let after_second = fs::read_to_string(pdir.join("PATCHES.txt")).unwrap();
        assert_eq!(after_second.matches("automatically generated").count(), 1);
        assert!(after_second.contains("Source: one.patch"));
        assert!(after_second.contains("Source: two.patch"));
    }

    #[test]
    fn append_after_package_scoped_write_shares_one_header() {
        // A package with its own patch already has a header-carrying PATCHES.txt;
        // a root patch appended to it must not add a second header.
        let work = tempdir().unwrap();
        let base = work.path().join("pkg");
        fs::create_dir_all(base.join("src")).unwrap();
        fs::write(base.join("src/Foo.php"), "a\nb\nc\n").unwrap();
        let pdir = tempdir().unwrap();
        let pkg = write_patch(
            pdir.path(),
            "fix.patch",
            "--- a/src/Foo.php\n+++ b/src/Foo.php\n@@ -1,3 +1,3 @@\n a\n-b\n+B\n c\n",
        );
        apply_package_patches(&base, "vendor/pkg", &[pkg], FailureMode::Abort, false).unwrap();

        let root = write_patch(pdir.path(), "top.patch", "");
        append_patches_txt(&base, &[&root]).unwrap();
        let report = fs::read_to_string(base.join("PATCHES.txt")).unwrap();
        assert_eq!(
            report.matches("automatically generated").count(),
            1,
            "{report}"
        );
        assert!(report.contains("Source: fix.patch") && report.contains("Source: top.patch"));
    }

    #[test]
    fn skip_report_suppresses_patches_txt() {
        let work = tempdir().unwrap();
        let base = work.path().join("pkg");
        fs::create_dir_all(base.join("src")).unwrap();
        fs::write(base.join("src/Foo.php"), "a\nb\nc\n").unwrap();
        let pdir = tempdir().unwrap();
        let patch = write_patch(
            pdir.path(),
            "fix.patch",
            "--- a/src/Foo.php\n+++ b/src/Foo.php\n@@ -1,3 +1,3 @@\n a\n-b\n+B\n c\n",
        );
        apply_package_patches(&base, "vendor/pkg", &[patch], FailureMode::Abort, true).unwrap();
        assert!(!base.join("PATCHES.txt").exists());
    }
}
